version: '3'
services:
  web:
    build: ./frontend
    ports:
        - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app      